version: "3"
services:
    api:
      build:
        context: ./api
        dockerfile: Dockerfile.api
      container_name: api
      depends_on:
        - redis
      volumes:
        - ./api:/app
      command: gunicorn --workers=3 --threads=2 --bind 0.0.0.0:5000 app:api.app
      ports:
        - "5000:5000"
    nginx:
      build:
        context: ./
        dockerfile: Dockerfile.nginx
      container_name: nginx
      depends_on:
        - api
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    redis:
      image: "redis:alpine"
